### ISSUE TITLE
BUG: Redirecting to `/newChat` if we try to go `/home` or `/userUpdate`

### ISSUE THREAD

**Issue by DevRohit06** [Qbtrix-Innovations/chatimg#3]
**Describe the bug**
After Login with email and password, before creating a new chat, if we try to go `/home` or even tries to update the profile it redirects to `/newChat`

**To Reproduce**
1.  Login using Email and password
2. before creating new chat, going `/home` with back button on upper right corner
3. or clicking on profilePhoto on `/newChat`  to go to `/userUpdate`
4. get Redirect to `/newChat`

**Expected behavior**
It should allow user to visit those pages and let them upate their profile information

**Screen Recording**

https://github.com/Qbtrix-Innovations/chatimg/assets/66678395/d1130723-bc52-44ae-b340-2fdd27e9b9e5

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Chrome
 - Version 120.0.6099.129

**Smartphone (please complete the following information):**
 - Device: Iphone SE
 - OS: 
 - Browser: Chrome
 - Version: 120.0.6099.129

**Comment by prakashUXtech** [comment]
check the user flow in figma - https://www.figma.com/proto/G6ZyihNyH0o25WsLC9q2OR/Qbtrix-Innovations?page-id=7915%3A61845&type=design&node-id=8468-213&viewport=199%2C598%2C0.66&t=sR7nrouq0aSmgRNI-1&scaling=min-zoom&starting-point-node-id=7941%3A866&mode=design
